name: Scrapping

on:
  schedule:
    - cron: '0 19 * * *'  # every day at 02.00 (WIB - 7)

jobs:
  save-data:
    runs-on: macOS-latest
    env:
      MONGODB_CONNECT : ${{secrets.MONGODB_CONNECT}}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@master
      - name: Install rvest package
        run: Rscript -e 'install.packages("rvest", dependencies = TRUE)'
      - name: Install mongolite package
        run: Rscript -e 'install.packages("mongolite", dependencies = TRUE)'
      - name: Getting data from islamicfinder.org/world/indonesia/ and add to database
        run: Rscript scrapping.R
